// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PhuonQuocChien106.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    [Migration("20230104012737_PQC0106")]
    partial class PQC0106
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("PhuonQuocChien106.Models.PQC0106", b =>
                {
                    b.Property<string>("PQCId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PQCGender")
                        .HasColumnType("TEXT");

                    b.Property<string>("PQCName")
                        .HasColumnType("TEXT");

                    b.HasKey("PQCId");

                    b.ToTable("PQC0106");
                });

            modelBuilder.Entity("PhuonQuocChien106.Models.UniversityPQC106", b =>
                {
                    b.Property<string>("UniversityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UniversityName")
                        .HasColumnType("TEXT");

                    b.HasKey("UniversityId");

                    b.ToTable("UniversityPQC106");
                });
#pragma warning restore 612, 618
        }
    }
}
